### ISSUE TITLE
Correctly handle when kuota service fails

### ISSUE THREAD

**Issue by resir014** [tibudiyanto/jakarta-vax-availability#53]
## Description

At the moment, the Kuota service fails intermittently, and by default we currently fall back to showing each of those facilities as having 0 kuota, which is obviously incorrect. We should handle this fallback state correctly.

![image](https://user-images.githubusercontent.com/5663877/124548265-af547180-de57-11eb-90ac-ae9c38e4db7e.png)

## Expected Behaviour

A fallback state should be displayed when Kuota service fails.

## Additional Information

Tweet thread: https://twitter.com/BukanYahya/status/1412283847341854720

**Comment by mathdroid** [comment]
Data source changes quite rapidly these days. Updated some of the API


<img width="1075" alt="Screen Shot 2021-07-06 at 4 45 51 PM" src="https://user-images.githubusercontent.com/3748658/124580117-03704d80-de7a-11eb-9a47-1b4f93a33942.png">

<img width="1104" alt="Screen Shot 2021-07-06 at 4 18 30 PM" src="https://user-images.githubusercontent.com/3748658/124580097-fc493f80-de79-11eb-9dbf-86608de74f2b.png">

**Comment by mathdroid** [comment]
![Uploading Screen Shot 2021-07-06 at 6.00.23 PM.png…]()

**Comment by mathdroid** [comment]
<img width="437" alt="Screen Shot 2021-07-06 at 6 00 23 PM" src="https://user-images.githubusercontent.com/3748658/124590991-f6595b80-de85-11eb-9bf8-b1fea6bd0aab.png">

**Comment by mathdroid** [comment]
The data source just changed again, now they correctly implement date and time with datetime format instead of string.

- [x] Added a new field, dateTimeISO for ISO time
- [x] Other fields are maintained at local time

https://jkt-vax-quota.vercel.app

<img width="1079" alt="Screen Shot 2021-07-08 at 2 46 25 PM" src="https://user-images.githubusercontent.com/3748658/124883356-705f2100-dffb-11eb-8603-22eae34e8d5d.png">

**Comment by mathdroid** [comment]
cc @resir014 @k1m0ch1
